
---
- hosts: mellon
  remote_user: root
  gather_facts: no
  tasks:
    - name: test connection compute
      ping:

    - name: check product version before upgrade
      shell: mstflint -d 12:00.0 q|grep Product
      register: pro_1
      become: yes

    - debug: msg="{{ pro_1.stdout }}"


    - name: check ethernet3f1 firmware version before upgrade
      shell: ethtool -i ens3f0|grep firmware-version
      register: ethtool3f0_1
      become: yes

    - debug: msg="{{ ethtool3f0_1.stdout }}"

    - name: check ethernet3f1 firmware version before upgrade
      shell: ethtool -i ens3f1|grep firmware-version
      register: ethtool3f1_1
      become: yes

    - debug: msg="{{ ethtool3f1_1.stdout }}"


    - name: install mellon
      shell: cd /root/MLNX_OFED_LINUX* && time ./mlnxofedinstall --add-kernel-support --skip-repo --force-fw-update --kernel 3.10.0-862.14.4.el7.x86_64
      become: yes
      register: myshell_output

    - name: copy the output to a local file
      copy:
        content: "{{ myshell_output.stdout }}"
        dest: "/tmp/shell.log"
      delegate_to: localhost

    - name: Reboot immediately after packages installed
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      become: yes
      register: task_reboot

    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 15
        timeout: 900
        become: yes

    - name: get uptime after reboot
      shell: /usr/bin/uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'
      changed_when: False
      register: uptime_after_reboot
      become: yes

    - debug: msg="{{ uptime_after_reboot.stdout }}"

    - name: check product version aftre upgrade
      shell: mstflint -d 12:00.0 q|grep Product
      register: pro_2
      become: yes

    - debug: msg="{{ pro_2.stdout }}"


    - name: check ethernet3f0 firmware version after upgrade
      shell: ethtool -i ens3f0|grep firmware-version
      register: ethtool3f0_2
      become: yes

    - debug: msg="{{ ethtool3f0_2.stdout }}"

    - name: check ethernet3f1 firmware version after upgrade
      shell: ethtool -i ens3f1|grep firmware-version
      register: ethtool3f1_2
      become: yes

    - debug: msg="{{ ethtool3f1_2.stdout }}"

